### ISSUE TITLE
Still working on HomeAssistant 2026.1.3

### ISSUE THREAD

**Issue by raymonvdm** [jslove/xap_controller#14]
I got the following error during a config check

`Configuration warnings
Platform error 'media_player' from integration 'xap_controller' - cannot import name 'SUPPORT_TURN_OFF' from 'homeassistant.components.media_player.const' (/usr/src/homeassistant/homeassistant/components/media_player/const.py)`

**Comment by jslove** [comment]
Sorry, I fixed that but didn't upload.  Coming shortly.
